.TH cl2nc "3.4.0" 10/03/2023

.SH NAME
cl2nc \- convert Vaisala CL51 and CL31 dat files to NetCDF

.SH SYNOPSIS
.B cl2nc
.RB [ -chq ]
.RB [ --debug ]
.RB [ --help ]
.I input
.I output

.SH DESCRIPTION

.IR input
is an input
.I .dat
file.
.IR output
is an output
.I .nc
file.
If directories are supplied for
.I input
and
.IR output ,
all
.IR ".dat " "and " .DAT
files in
.I input
are converted to
.I .nc
files in
.IR output .

.SH OPTIONS

.TP
.B -c
Enable checksum verification (slow).
.TP
.B --debug
Enable debugging output.
.TP
.TP
.BR -h , " --help"
Show help message and exit.
.TP
.B -q
Run quietly (suppress output).

.SH EXAMPLES

.B cl2nc input.dat outout.nc

Convert
.I input.dat
to
.IR output.nc .

.B cl2nc in out

Convert dat files in the directory
.I in
to NetCDF files in the directory
.IR out .

.SH COPYRIGHT

Copyright (C) 2018-2023 Peter Kuma.
.PP
This program is available under the terms of an MIT license (see LICENSE.md in the distribution).

.SH SEE ALSO

See <https://github.com/peterkuma/cl2nc>
for more information about
.BR cl2nc .
